name: Create Release

on:
  push:
    branches:
      - feature/update-icons

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_BOT }}
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          tag_prefix: ""
          release_branches: "feature/update-icons"
          github_token: ${{ secrets.TOKEN_BOT }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN_BOT }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Update Main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_BOT }}
          branch: "main"
