name: Update Icons

on:
  workflow_dispatch:
  schedule:
    - cron: 0 14 * * 0


jobs:
  update-submodules:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0]
        laravel: [^8.0]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_BOT }}
          persist-credentials: false
          fetch-depth: 0

      - name: Update submodule
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_BOT }}
          repository: simple-icons/simple-icons
          ref: 'master'
          path: ./dist

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --dev

      - name: Generate icons
        run: composer run generate-icons

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN_BOT }}
          author_email: ${{ secrets.BOT_EMAIL }}
          author_name: ${{ secrets.BOT_NAME }}
          branch: feature/update-icons
          message: "feat(svg): update simple icons"
